package visual;

import modelo.Curso;

/**
 * La clase VentanaAlumno representa la interfaz gráfica de usuario para la
 * visualización de información relacionada con los alumnos.
 */
public class VentanaAlumno extends javax.swing.JFrame {

    /**
     * Crea una nueva instancia de VentanaAlumno.
     */
    public VentanaAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAlumno = new javax.swing.JPanel();
        jTabbedPaneVentanaAlumno = new javax.swing.JTabbedPane();
        jPanelInscripciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCursosDisponibles = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButtonFinalizarInscripcion = new javax.swing.JButton();
        jButtonAgregarCurso = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListCursosAgregados = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jButtonQuitarCurso = new javax.swing.JButton();
        jPanelEstadoCursadas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListCursosInscriptos = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListCursosAprobados = new javax.swing.JList<>();
        jPanelMiCuenta = new javax.swing.JPanel();
        jLabelDatosUsuario = new javax.swing.JLabel();
        jLabelNombreAlumno = new javax.swing.JLabel();
        jLabelApellidoAlumno = new javax.swing.JLabel();
        jLabelDniAlumno = new javax.swing.JLabel();
        jButtonCambiarContraseña = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(414, 392));

        jScrollPane1.setViewportView(jListCursosDisponibles);

        jLabel1.setText("Cursos disponibles:");

        jButtonFinalizarInscripcion.setText("Finalizar inscripción");
        jButtonFinalizarInscripcion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonFinalizarInscripcion.setEnabled(false);
        jButtonFinalizarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarInscripcionActionPerformed(evt);
            }
        });

        jButtonAgregarCurso.setText("Agregar >>");
        jButtonAgregarCurso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAgregarCurso.setEnabled(false);
        jButtonAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCursoActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jListCursosAgregados);

        jLabel4.setText("Cursos agregados:");

        jButtonQuitarCurso.setText("Quitar <<");
        jButtonQuitarCurso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonQuitarCurso.setEnabled(false);

        javax.swing.GroupLayout jPanelInscripcionesLayout = new javax.swing.GroupLayout(jPanelInscripciones);
        jPanelInscripciones.setLayout(jPanelInscripcionesLayout);
        jPanelInscripcionesLayout.setHorizontalGroup(
            jPanelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInscripcionesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInscripcionesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonFinalizarInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInscripcionesLayout.createSequentialGroup()
                        .addGroup(jPanelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInscripcionesLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonQuitarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        jPanelInscripcionesLayout.setVerticalGroup(
            jPanelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInscripcionesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInscripcionesLayout.createSequentialGroup()
                        .addComponent(jButtonAgregarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonQuitarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addGap(43, 43, 43)
                .addComponent(jButtonFinalizarInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPaneVentanaAlumno.addTab("Inscripciones", jPanelInscripciones);

        jLabel2.setText("Cursos inscriptos:");

        jLabel3.setText("Cursos aprobados:");

        jScrollPane5.setViewportView(jListCursosInscriptos);

        jScrollPane6.setViewportView(jListCursosAprobados);

        javax.swing.GroupLayout jPanelEstadoCursadasLayout = new javax.swing.GroupLayout(jPanelEstadoCursadas);
        jPanelEstadoCursadas.setLayout(jPanelEstadoCursadasLayout);
        jPanelEstadoCursadasLayout.setHorizontalGroup(
            jPanelEstadoCursadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoCursadasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelEstadoCursadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanelEstadoCursadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30))
        );
        jPanelEstadoCursadasLayout.setVerticalGroup(
            jPanelEstadoCursadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoCursadasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelEstadoCursadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelEstadoCursadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPaneVentanaAlumno.addTab("Estado Cursadas", jPanelEstadoCursadas);

        jLabelDatosUsuario.setText("Datos del usuario");

        jButtonCambiarContraseña.setText("Cambiar contraseña");
        jButtonCambiarContraseña.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMiCuentaLayout = new javax.swing.GroupLayout(jPanelMiCuenta);
        jPanelMiCuenta.setLayout(jPanelMiCuentaLayout);
        jPanelMiCuentaLayout.setHorizontalGroup(
            jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                .addGroup(jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCambiarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelDniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanelMiCuentaLayout.setVerticalGroup(
            jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelDatosUsuario)
                .addGap(26, 26, 26)
                .addComponent(jLabelNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonCambiarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTabbedPaneVentanaAlumno.addTab("Mi Cuenta", jPanelMiCuenta);

        javax.swing.GroupLayout jPanelAlumnoLayout = new javax.swing.GroupLayout(jPanelAlumno);
        jPanelAlumno.setLayout(jPanelAlumnoLayout);
        jPanelAlumnoLayout.setHorizontalGroup(
            jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVentanaAlumno)
        );
        jPanelAlumnoLayout.setVerticalGroup(
            jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVentanaAlumno)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFinalizarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarInscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFinalizarInscripcionActionPerformed

    private void jButtonAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarCursoActionPerformed

    private void jButtonCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCambiarContraseñaActionPerformed

    /**
     * Método principal para ejecutar la aplicación. Crea una instancia de VentanaAlumno y la hace visible.
     *
     * @param args los argumentos de la línea de comandos (no se utilizan en esta aplicación).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAgregarCurso;
    public javax.swing.JButton jButtonCambiarContraseña;
    public javax.swing.JButton jButtonFinalizarInscripcion;
    public javax.swing.JButton jButtonQuitarCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabelApellidoAlumno;
    private javax.swing.JLabel jLabelDatosUsuario;
    public javax.swing.JLabel jLabelDniAlumno;
    public javax.swing.JLabel jLabelNombreAlumno;
    public javax.swing.JList<Curso> jListCursosAgregados;
    public javax.swing.JList<Curso> jListCursosAprobados;
    public javax.swing.JList<Curso> jListCursosDisponibles;
    public javax.swing.JList<Curso> jListCursosInscriptos;
    private javax.swing.JPanel jPanelAlumno;
    private javax.swing.JPanel jPanelEstadoCursadas;
    public javax.swing.JPanel jPanelInscripciones;
    private javax.swing.JPanel jPanelMiCuenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTabbedPane jTabbedPaneVentanaAlumno;
    // End of variables declaration//GEN-END:variables
}
