package visual;

import modelo.Alumno;
import modelo.Curso;

/**
 * La clase VentanaDocente representa la interfaz gráfica de usuario para el
 * docente.
 */
public class VentanaDocente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaDocente
     */
    public VentanaDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCalificar = new javax.swing.ButtonGroup();
        jPanelDocente = new javax.swing.JPanel();
        jTabbedPaneVentanaDocente = new javax.swing.JTabbedPane();
        jPanelCrearCurso = new javax.swing.JPanel();
        jLabelNombreCurso = new javax.swing.JLabel();
        jTextFieldNombreCurso = new javax.swing.JTextField();
        jLabelDescripcionCurso = new javax.swing.JLabel();
        jButtonProponerCurso = new javax.swing.JButton();
        jLabelRequisitoCursada = new javax.swing.JLabel();
        jComboBoxCursosRequeridos = new javax.swing.JComboBox<>();
        jLabelErrorNombreCurso = new javax.swing.JLabel();
        jLabelErrorDescripcionCurso = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaDescripcionCurso = new javax.swing.JTextArea();
        jPanelCalificarCurso = new javax.swing.JPanel();
        jLabelListadoCursos = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListCursosCalificar = new javax.swing.JList<>();
        jLabelListadoAlumnos = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListAlumnosCalificar = new javax.swing.JList<>();
        jLabelNotaCursada = new javax.swing.JLabel();
        jRadioButtonCursadaAprobada = new javax.swing.JRadioButton();
        jRadioButtonCursadaDesaprobada = new javax.swing.JRadioButton();
        jButtonFinalizarCurso = new javax.swing.JButton();
        jButtonCalificar = new javax.swing.JButton();
        jButtonCerrarInscripcion = new javax.swing.JButton();
        jTextFieldCalificado = new javax.swing.JTextField();
        jPanelCursosFinalizados = new javax.swing.JPanel();
        jLabelListaCursos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCursosFinalizados = new javax.swing.JList<>();
        jButtonReiniciarCurso = new javax.swing.JButton();
        jPanelPropuestosCancelados = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCursosPropuestos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCursosCancelados = new javax.swing.JList<>();
        jPanelMiCuenta = new javax.swing.JPanel();
        jLabelDatosUsuario = new javax.swing.JLabel();
        jLabelNombreDocente = new javax.swing.JLabel();
        jLabelApellidoDocente = new javax.swing.JLabel();
        jLabelDniDocente = new javax.swing.JLabel();
        jButtonCambiarContraseña = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDocente.setPreferredSize(new java.awt.Dimension(414, 392));

        jLabelNombreCurso.setText("Nombre del Curso");

        jTextFieldNombreCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreCursoActionPerformed(evt);
            }
        });
        jTextFieldNombreCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreCursoKeyTyped(evt);
            }
        });

        jLabelDescripcionCurso.setText("Descripción");

        jButtonProponerCurso.setText("Proponer");
        jButtonProponerCurso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonProponerCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProponerCursoActionPerformed(evt);
            }
        });

        jLabelRequisitoCursada.setText("Cursos requeridos");

        jComboBoxCursosRequeridos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));

        jTextAreaDescripcionCurso.setColumns(20);
        jTextAreaDescripcionCurso.setLineWrap(true);
        jTextAreaDescripcionCurso.setRows(5);
        jTextAreaDescripcionCurso.setWrapStyleWord(true);
        jTextAreaDescripcionCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaDescripcionCursoKeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(jTextAreaDescripcionCurso);

        javax.swing.GroupLayout jPanelCrearCursoLayout = new javax.swing.GroupLayout(jPanelCrearCurso);
        jPanelCrearCurso.setLayout(jPanelCrearCursoLayout);
        jPanelCrearCursoLayout.setHorizontalGroup(
            jPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCrearCursoLayout.createSequentialGroup()
                        .addGroup(jPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescripcionCurso)
                            .addComponent(jLabelNombreCurso))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreCurso)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))
                    .addGroup(jPanelCrearCursoLayout.createSequentialGroup()
                        .addComponent(jLabelRequisitoCursada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCursosRequeridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonProponerCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorDescripcionCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jLabelErrorNombreCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCrearCursoLayout.setVerticalGroup(
            jPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearCursoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreCurso)
                    .addComponent(jLabelErrorNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescripcionCurso)
                    .addComponent(jLabelErrorDescripcionCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRequisitoCursada)
                    .addGroup(jPanelCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxCursosRequeridos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonProponerCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(147, 147, 147))
        );

        jTabbedPaneVentanaDocente.addTab("Crear Curso", jPanelCrearCurso);

        jLabelListadoCursos.setText("Cursos Hab/Cerrados");

        jScrollPane4.setViewportView(jListCursosCalificar);

        jLabelListadoAlumnos.setText("Lista de Alumnos");

        jScrollPane5.setViewportView(jListAlumnosCalificar);

        jLabelNotaCursada.setText("Estado:");

        buttonGroupCalificar.add(jRadioButtonCursadaAprobada);
        jRadioButtonCursadaAprobada.setText("Aprobado");

        buttonGroupCalificar.add(jRadioButtonCursadaDesaprobada);
        jRadioButtonCursadaDesaprobada.setText("Desaprobado");
        jRadioButtonCursadaDesaprobada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCursadaDesaprobadaActionPerformed(evt);
            }
        });

        jButtonFinalizarCurso.setText("Finalizar Curso");
        jButtonFinalizarCurso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonCalificar.setText("Calificar");
        jButtonCalificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalificarActionPerformed(evt);
            }
        });

        jButtonCerrarInscripcion.setText("Cerrar Inscripcion");
        jButtonCerrarInscripcion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCerrarInscripcion.setEnabled(false);
        jButtonCerrarInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarInscripcionActionPerformed(evt);
            }
        });

        jTextFieldCalificado.setEditable(false);
        jTextFieldCalificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCalificadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCalificarCursoLayout = new javax.swing.GroupLayout(jPanelCalificarCurso);
        jPanelCalificarCurso.setLayout(jPanelCalificarCursoLayout);
        jPanelCalificarCursoLayout.setHorizontalGroup(
            jPanelCalificarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCalificarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListadoCursos)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButtonCerrarInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelCalificarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                        .addGroup(jPanelCalificarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanelCalificarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                                        .addComponent(jLabelListadoAlumnos)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanelCalificarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                                        .addGroup(jPanelCalificarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonCursadaAprobada)
                                            .addComponent(jRadioButtonCursadaDesaprobada))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                                        .addComponent(jButtonCalificar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonFinalizarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))))
                        .addContainerGap())
                    .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelNotaCursada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCalificado, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelCalificarCursoLayout.setVerticalGroup(
            jPanelCalificarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCalificarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelListadoCursos)
                    .addComponent(jLabelListadoAlumnos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalificarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCerrarInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(jPanelCalificarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNotaCursada)
                            .addComponent(jTextFieldCalificado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonCursadaAprobada)
                        .addGroup(jPanelCalificarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCalificarCursoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonCursadaDesaprobada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCalificar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCalificarCursoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonFinalizarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))))
        );

        jTabbedPaneVentanaDocente.addTab("Calificar", jPanelCalificarCurso);

        jLabelListaCursos.setText("Cursos Finalizados");

        jScrollPane3.setViewportView(jListCursosFinalizados);

        jButtonReiniciarCurso.setText("Reiniciar Curso");
        jButtonReiniciarCurso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonReiniciarCurso.setEnabled(false);

        javax.swing.GroupLayout jPanelCursosFinalizadosLayout = new javax.swing.GroupLayout(jPanelCursosFinalizados);
        jPanelCursosFinalizados.setLayout(jPanelCursosFinalizadosLayout);
        jPanelCursosFinalizadosLayout.setHorizontalGroup(
            jPanelCursosFinalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCursosFinalizadosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelCursosFinalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCursosFinalizadosLayout.createSequentialGroup()
                        .addGroup(jPanelCursosFinalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonReiniciarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(jPanelCursosFinalizadosLayout.createSequentialGroup()
                        .addComponent(jLabelListaCursos)
                        .addContainerGap(358, Short.MAX_VALUE))))
        );
        jPanelCursosFinalizadosLayout.setVerticalGroup(
            jPanelCursosFinalizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCursosFinalizadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelListaCursos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(jButtonReiniciarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jTabbedPaneVentanaDocente.addTab("Finalizados", jPanelCursosFinalizados);

        jLabel5.setText("Cursos Propuestos");

        jLabel6.setText("Cursos Cancelados");

        jScrollPane1.setViewportView(jListCursosPropuestos);

        jScrollPane2.setViewportView(jListCursosCancelados);

        javax.swing.GroupLayout jPanelPropuestosCanceladosLayout = new javax.swing.GroupLayout(jPanelPropuestosCancelados);
        jPanelPropuestosCancelados.setLayout(jPanelPropuestosCanceladosLayout);
        jPanelPropuestosCanceladosLayout.setHorizontalGroup(
            jPanelPropuestosCanceladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPropuestosCanceladosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelPropuestosCanceladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanelPropuestosCanceladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanelPropuestosCanceladosLayout.setVerticalGroup(
            jPanelPropuestosCanceladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPropuestosCanceladosLayout.createSequentialGroup()
                .addGroup(jPanelPropuestosCanceladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPropuestosCanceladosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanelPropuestosCanceladosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPropuestosCanceladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPaneVentanaDocente.addTab("Propuestos/Cancelados", jPanelPropuestosCancelados);

        jLabelDatosUsuario.setText("Datos del usuario");

        jButtonCambiarContraseña.setText("Cambiar contraseña");
        jButtonCambiarContraseña.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiarContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMiCuentaLayout = new javax.swing.GroupLayout(jPanelMiCuenta);
        jPanelMiCuenta.setLayout(jPanelMiCuentaLayout);
        jPanelMiCuentaLayout.setHorizontalGroup(
            jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                .addGroup(jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCambiarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelApellidoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelDniDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanelMiCuentaLayout.setVerticalGroup(
            jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelDatosUsuario)
                .addGap(26, 26, 26)
                .addComponent(jLabelNombreDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelApellidoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDniDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonCambiarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPaneVentanaDocente.addTab("Mi Cuenta", jPanelMiCuenta);

        javax.swing.GroupLayout jPanelDocenteLayout = new javax.swing.GroupLayout(jPanelDocente);
        jPanelDocente.setLayout(jPanelDocenteLayout);
        jPanelDocenteLayout.setHorizontalGroup(
            jPanelDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVentanaDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelDocenteLayout.setVerticalGroup(
            jPanelDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneVentanaDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProponerCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProponerCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonProponerCursoActionPerformed

    private void jButtonCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalificarActionPerformed

    private void jRadioButtonCursadaDesaprobadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCursadaDesaprobadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCursadaDesaprobadaActionPerformed

    private void jButtonCerrarInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarInscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCerrarInscripcionActionPerformed

    private void jTextFieldCalificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCalificadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCalificadoActionPerformed

    private void jButtonCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiarContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCambiarContraseñaActionPerformed

    /**
     * Método invocado cuando se escribe en el campo de texto del nombre del
     * curso. Limpia el mensaje de error asociado al campo.
     *
     * @param evt el evento de teclado generado
     */
    private void jTextFieldNombreCursoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreCursoKeyTyped
        // Limpiar mensaje de error
        jLabelErrorNombreCurso.setText("");
    }//GEN-LAST:event_jTextFieldNombreCursoKeyTyped

    /**
     * Método invocado cuando se escribe en el área de texto de la descripción
     * del curso. Limpia el mensaje de error asociado al área de texto.
     *
     * @param evt el evento de teclado generado
     */
    private void jTextAreaDescripcionCursoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaDescripcionCursoKeyTyped
        // Limpiar mensaje de error
        jLabelErrorDescripcionCurso.setText("");
    }//GEN-LAST:event_jTextAreaDescripcionCursoKeyTyped

    private void jTextFieldNombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCursoActionPerformed

    /**
     * Método principal para ejecutar la aplicación. 
     *
     * @param args los argumentos de la línea de comandos (no se utilizan en
     * esta aplicación)
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroupCalificar;
    public javax.swing.JButton jButtonCalificar;
    public javax.swing.JButton jButtonCambiarContraseña;
    public javax.swing.JButton jButtonCerrarInscripcion;
    public javax.swing.JButton jButtonFinalizarCurso;
    public javax.swing.JButton jButtonProponerCurso;
    public javax.swing.JButton jButtonReiniciarCurso;
    public javax.swing.JComboBox<String> jComboBoxCursosRequeridos;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabelApellidoDocente;
    private javax.swing.JLabel jLabelDatosUsuario;
    private javax.swing.JLabel jLabelDescripcionCurso;
    public javax.swing.JLabel jLabelDniDocente;
    public javax.swing.JLabel jLabelErrorDescripcionCurso;
    public javax.swing.JLabel jLabelErrorNombreCurso;
    private javax.swing.JLabel jLabelListaCursos;
    private javax.swing.JLabel jLabelListadoAlumnos;
    private javax.swing.JLabel jLabelListadoCursos;
    private javax.swing.JLabel jLabelNombreCurso;
    public javax.swing.JLabel jLabelNombreDocente;
    private javax.swing.JLabel jLabelNotaCursada;
    private javax.swing.JLabel jLabelRequisitoCursada;
    public javax.swing.JList<Alumno> jListAlumnosCalificar;
    public javax.swing.JList<Curso> jListCursosCalificar;
    public javax.swing.JList<Curso> jListCursosCancelados;
    public javax.swing.JList<Curso> jListCursosFinalizados;
    public javax.swing.JList<Curso> jListCursosPropuestos;
    private javax.swing.JPanel jPanelCalificarCurso;
    private javax.swing.JPanel jPanelCrearCurso;
    private javax.swing.JPanel jPanelCursosFinalizados;
    private javax.swing.JPanel jPanelDocente;
    private javax.swing.JPanel jPanelMiCuenta;
    private javax.swing.JPanel jPanelPropuestosCancelados;
    public javax.swing.JRadioButton jRadioButtonCursadaAprobada;
    public javax.swing.JRadioButton jRadioButtonCursadaDesaprobada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTabbedPane jTabbedPaneVentanaDocente;
    public javax.swing.JTextArea jTextAreaDescripcionCurso;
    public javax.swing.JTextField jTextFieldCalificado;
    public javax.swing.JTextField jTextFieldNombreCurso;
    // End of variables declaration//GEN-END:variables
}
