package visual;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import modelo.Curso;

/**
 * Clase que representa la ventana de administrador de la aplicación.
 */
public class VentanaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdmin
     */
    public VentanaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoUsuario = new javax.swing.ButtonGroup();
        jPanelAdmin = new javax.swing.JPanel();
        jTabbedPaneAdmin = new javax.swing.JTabbedPane();
        jPanelRegistroUser = new javax.swing.JPanel();
        jLabelNombreUsuario = new javax.swing.JLabel();
        jLabelDNIUsuario = new javax.swing.JLabel();
        jTextFieldNombreUser = new javax.swing.JTextField();
        jTextFieldDNIUser = new javax.swing.JTextField();
        jPanelTipoUsuario = new javax.swing.JPanel();
        jRadioButtonCuentaAlumno = new javax.swing.JRadioButton();
        jRadioButtonCuentaDocente = new javax.swing.JRadioButton();
        jButtonCrearUsuario = new javax.swing.JButton();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelErrorNombre = new javax.swing.JLabel();
        jLabelErrorApellido = new javax.swing.JLabel();
        jLabelErrorDni = new javax.swing.JLabel();
        jPanelEstadoCuenta = new javax.swing.JPanel();
        jTextFieldBuscarUsuario = new javax.swing.JTextField();
        jButtonBuscarUsuario = new javax.swing.JButton();
        jButtonBlanquearClave = new javax.swing.JButton();
        jButtonSuspenderCuenta = new javax.swing.JButton();
        jLabelBusquedaUser = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaEstadoCuenta = new javax.swing.JTextArea();
        jButtonReactivarCuenta = new javax.swing.JButton();
        jLabelErrorBuscarUsuario = new javax.swing.JLabel();
        jPanelCursos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCursos = new javax.swing.JList<>();
        jLabelDescripcionCursos = new javax.swing.JLabel();
        jLabelModificarEstado = new javax.swing.JLabel();
        jComboBoxModificarEstadoCurso = new javax.swing.JComboBox<>();
        jLabelTopeAlumnos = new javax.swing.JLabel();
        jTextFieldTopeAlumnos = new javax.swing.JTextField();
        jButtonModificarEstadoCurso = new javax.swing.JButton();
        jLabelFiltroCurso = new javax.swing.JLabel();
        jComboBoxFiltroCursos = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDescripcionCurso = new javax.swing.JTextArea();
        jLabelErrorTopeAlumnos = new javax.swing.JLabel();
        jPanelListadoUsuarios = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListadoUsuarios = new javax.swing.JTable();
        jPanelMiCuenta = new javax.swing.JPanel();
        jLabelDatosUsuario = new javax.swing.JLabel();
        jLabelNombreAdmin = new javax.swing.JLabel();
        jLabelApellidoAdmin = new javax.swing.JLabel();
        jLabelDniAdmin = new javax.swing.JLabel();
        jButtonCambiarContraseña = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelRegistroUser.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNombreUsuario.setText("Nombre");

        jLabelDNIUsuario.setText("DNI");

        jTextFieldNombreUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreUserActionPerformed(evt);
            }
        });
        jTextFieldNombreUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreUserKeyTyped(evt);
            }
        });

        jTextFieldDNIUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDNIUserKeyTyped(evt);
            }
        });

        jPanelTipoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Usuario"));

        buttonGroupTipoUsuario.add(jRadioButtonCuentaAlumno);
        jRadioButtonCuentaAlumno.setText("Cuenta Alumno");
        jRadioButtonCuentaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCuentaAlumnoActionPerformed(evt);
            }
        });

        buttonGroupTipoUsuario.add(jRadioButtonCuentaDocente);
        jRadioButtonCuentaDocente.setText("Cuenta Docente");

        jButtonCrearUsuario.setText("Crear Usuario");
        jButtonCrearUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCrearUsuario.setEnabled(false);
        jButtonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTipoUsuarioLayout = new javax.swing.GroupLayout(jPanelTipoUsuario);
        jPanelTipoUsuario.setLayout(jPanelTipoUsuarioLayout);
        jPanelTipoUsuarioLayout.setHorizontalGroup(
            jPanelTipoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoUsuarioLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanelTipoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTipoUsuarioLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTipoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jRadioButtonCuentaDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonCuentaAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTipoUsuarioLayout.setVerticalGroup(
            jPanelTipoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonCuentaAlumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCuentaDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelApellido.setText("Apellido");

        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });
        jTextFieldApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistroUserLayout = new javax.swing.GroupLayout(jPanelRegistroUser);
        jPanelRegistroUser.setLayout(jPanelRegistroUserLayout);
        jPanelRegistroUserLayout.setHorizontalGroup(
            jPanelRegistroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroUserLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanelRegistroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegistroUserLayout.createSequentialGroup()
                        .addComponent(jLabelDNIUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldDNIUser))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegistroUserLayout.createSequentialGroup()
                        .addComponent(jLabelApellido)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldApellido))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRegistroUserLayout.createSequentialGroup()
                        .addComponent(jLabelNombreUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jLabelErrorApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelErrorDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelRegistroUserLayout.setVerticalGroup(
            jPanelRegistroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistroUserLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelRegistroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRegistroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNombreUsuario)
                        .addComponent(jTextFieldNombreUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistroUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNIUsuario)
                    .addComponent(jTextFieldDNIUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorDni, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jPanelTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPaneAdmin.addTab("Registrar Usuario", jPanelRegistroUser);

        jPanelEstadoCuenta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldBuscarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarUsuarioKeyTyped(evt);
            }
        });

        jButtonBuscarUsuario.setText("Buscar Usuario");
        jButtonBuscarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonBlanquearClave.setText("Blanquear Clave");
        jButtonBlanquearClave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBlanquearClave.setEnabled(false);

        jButtonSuspenderCuenta.setText("Suspender Cuenta");
        jButtonSuspenderCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSuspenderCuenta.setEnabled(false);

        jLabelBusquedaUser.setText("Ingrese el DNI del usuario");

        jTextAreaEstadoCuenta.setColumns(20);
        jTextAreaEstadoCuenta.setRows(5);
        jScrollPane3.setViewportView(jTextAreaEstadoCuenta);

        jButtonReactivarCuenta.setText("Reactivar Cuenta");
        jButtonReactivarCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonReactivarCuenta.setEnabled(false);

        javax.swing.GroupLayout jPanelEstadoCuentaLayout = new javax.swing.GroupLayout(jPanelEstadoCuenta);
        jPanelEstadoCuenta.setLayout(jPanelEstadoCuentaLayout);
        jPanelEstadoCuentaLayout.setHorizontalGroup(
            jPanelEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEstadoCuentaLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanelEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBusquedaUser)
                    .addGroup(jPanelEstadoCuentaLayout.createSequentialGroup()
                        .addGroup(jPanelEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelEstadoCuentaLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabelErrorBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldBuscarUsuario, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSuspenderCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jButtonBlanquearClave, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jButtonReactivarCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBuscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(49, 49, 49))
        );
        jPanelEstadoCuentaLayout.setVerticalGroup(
            jPanelEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoCuentaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelBusquedaUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanelEstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEstadoCuentaLayout.createSequentialGroup()
                        .addComponent(jButtonBlanquearClave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSuspenderCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonReactivarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPaneAdmin.addTab("Gestión de Cuentas", jPanelEstadoCuenta);

        jPanelCursos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jListCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListCursos);

        jLabelDescripcionCursos.setText("Descripción del Curso");

        jLabelModificarEstado.setText("Modificar Estado");

        jComboBoxModificarEstadoCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propuesto", "Habilitado", "Cerrado", "Cancelado", "Finalizado" }));
        jComboBoxModificarEstadoCurso.setSelectedIndex(-1);
        jComboBoxModificarEstadoCurso.setEnabled(false);
        jComboBoxModificarEstadoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModificarEstadoCursoActionPerformed(evt);
            }
        });

        jLabelTopeAlumnos.setText("Tope de Alumnos");

        jTextFieldTopeAlumnos.setEnabled(false);
        jTextFieldTopeAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTopeAlumnosActionPerformed(evt);
            }
        });
        jTextFieldTopeAlumnos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTopeAlumnosKeyTyped(evt);
            }
        });

        jButtonModificarEstadoCurso.setText("Aplicar");
        jButtonModificarEstadoCurso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonModificarEstadoCurso.setEnabled(false);
        jButtonModificarEstadoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarEstadoCursoActionPerformed(evt);
            }
        });

        jLabelFiltroCurso.setText("Filtrar cursos por estado:");

        jComboBoxFiltroCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propuesto", "Habilitado", "Cerrado", "Cancelado", "Finalizado" }));
        jComboBoxFiltroCursos.setSelectedIndex(-1);
        jComboBoxFiltroCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBoxFiltroCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFiltroCursosActionPerformed(evt);
            }
        });

        jTextAreaDescripcionCurso.setColumns(20);
        jTextAreaDescripcionCurso.setLineWrap(true);
        jTextAreaDescripcionCurso.setRows(5);
        jTextAreaDescripcionCurso.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextAreaDescripcionCurso);

        javax.swing.GroupLayout jPanelCursosLayout = new javax.swing.GroupLayout(jPanelCursos);
        jPanelCursos.setLayout(jPanelCursosLayout);
        jPanelCursosLayout.setHorizontalGroup(
            jPanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCursosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCursosLayout.createSequentialGroup()
                        .addComponent(jLabelFiltroCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanelCursosLayout.createSequentialGroup()
                        .addGroup(jPanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxFiltroCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCursosLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonModificarEstadoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDescripcionCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTopeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxModificarEstadoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelModificarEstado)
                                    .addGroup(jPanelCursosLayout.createSequentialGroup()
                                        .addComponent(jTextFieldTopeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelErrorTopeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 61, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCursosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))))))
        );
        jPanelCursosLayout.setVerticalGroup(
            jPanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCursosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCursosLayout.createSequentialGroup()
                        .addComponent(jLabelFiltroCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxFiltroCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCursosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelDescripcionCursos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCursosLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelModificarEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxModificarEstadoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTopeAlumnos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTopeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorTopeAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificarEstadoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jTabbedPaneAdmin.addTab("Cursos", jPanelCursos);

        jTableListadoUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Apellido", "Nombre", "DNI", "Perfil", "Estado cuenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableListadoUsuarios);

        javax.swing.GroupLayout jPanelListadoUsuariosLayout = new javax.swing.GroupLayout(jPanelListadoUsuarios);
        jPanelListadoUsuarios.setLayout(jPanelListadoUsuariosLayout);
        jPanelListadoUsuariosLayout.setHorizontalGroup(
            jPanelListadoUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
        );
        jPanelListadoUsuariosLayout.setVerticalGroup(
            jPanelListadoUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoUsuariosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneAdmin.addTab("Usuarios", jPanelListadoUsuarios);

        jLabelDatosUsuario.setText("Datos del usuario");

        jButtonCambiarContraseña.setText("Cambiar contraseña");
        jButtonCambiarContraseña.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanelMiCuentaLayout = new javax.swing.GroupLayout(jPanelMiCuenta);
        jPanelMiCuenta.setLayout(jPanelMiCuentaLayout);
        jPanelMiCuentaLayout.setHorizontalGroup(
            jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                .addGroup(jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelApellidoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDniAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMiCuentaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonCambiarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanelMiCuentaLayout.setVerticalGroup(
            jPanelMiCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMiCuentaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelDatosUsuario)
                .addGap(26, 26, 26)
                .addComponent(jLabelNombreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelApellidoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelDniAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButtonCambiarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPaneAdmin.addTab("Mi cuenta", jPanelMiCuenta);

        javax.swing.GroupLayout jPanelAdminLayout = new javax.swing.GroupLayout(jPanelAdmin);
        jPanelAdmin.setLayout(jPanelAdminLayout);
        jPanelAdminLayout.setHorizontalGroup(
            jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminLayout.createSequentialGroup()
                .addComponent(jTabbedPaneAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelAdminLayout.setVerticalGroup(
            jPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCursosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListCursosMouseClicked

    private void jComboBoxModificarEstadoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModificarEstadoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxModificarEstadoCursoActionPerformed

    private void jTextFieldTopeAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTopeAlumnosActionPerformed
        // chequear si esta bien escrito, excepciones
    }//GEN-LAST:event_jTextFieldTopeAlumnosActionPerformed

    private void jTextFieldNombreUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreUserActionPerformed

    private void jButtonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearUsuarioActionPerformed

    }//GEN-LAST:event_jButtonCrearUsuarioActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jRadioButtonCuentaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCuentaAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCuentaAlumnoActionPerformed

    private void jComboBoxFiltroCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFiltroCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFiltroCursosActionPerformed

    private void jButtonModificarEstadoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarEstadoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarEstadoCursoActionPerformed

    /**
     * Maneja el evento de tecla presionada en el campo de búsqueda de usuario.
     * Limita la entrada a caracteres numéricos y no más de 8 dígitos. Emite un
     * sonido de advertencia si se excede el límite. Limpia el mensaje de error
     * asociado al campo.
     *
     * @param evt El evento de tecla presionada.
     */
    private void jTextFieldBuscarUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarUsuarioKeyTyped
        char c = evt.getKeyChar();
        //solo hasta 8 numeros
        if (!Character.isDigit(c) || (jTextFieldBuscarUsuario.getText().length() >= 8)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        // Limpiar mensaje de error
        jLabelErrorBuscarUsuario.setText("");
    }//GEN-LAST:event_jTextFieldBuscarUsuarioKeyTyped

    /**
     * Maneja el evento de tecla presionada en el campo de nombre de usuario.
     * Limita la entrada a letras, espacios y caracteres especiales, con una
     * longitud máxima de 40 caracteres. Emite un sonido de advertencia si se
     * excede el límite. Limpia el mensaje de error asociado al campo.
     *
     * @param evt El evento de tecla presionada.
     */
    private void jTextFieldNombreUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreUserKeyTyped
        char c = evt.getKeyChar();
        // Verificar si la tecla presionada no es una letra, un espacio, o un carácter especial, o si se excede la longitud máxima
        if (!(Character.isLetter(c) || c == ' ' || "áéíóúÁÉÍÓÚüÜñÑ'".indexOf(c) != -1) || jTextFieldNombreUser.getText().length() >= 40) {
            evt.consume(); // Consumir el evento para evitar que el carácter sea ingresado
            // Solo emitir el beep si no es la tecla de borrar
            if (c != KeyEvent.VK_BACK_SPACE) {
                Toolkit.getDefaultToolkit().beep();
            }
        }
        // Limpiar mensaje de error
        jLabelErrorNombre.setText("");
    }//GEN-LAST:event_jTextFieldNombreUserKeyTyped

    /**
     * Maneja el evento de tecla presionada en el campo de apellido. Limita la
     * entrada a letras, espacios y caracteres especiales, con una longitud
     * máxima de 40 caracteres. Emite un sonido de advertencia si se excede el
     * límite. Limpia el mensaje de error asociado al campo.
     *
     * @param evt El evento de tecla presionada.
     */
    private void jTextFieldApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoKeyTyped
        char c = evt.getKeyChar();
        //solo letras
        if (!(Character.isLetter(c) || c == ' ' || "áéíóúÁÉÍÓÚüÜñÑ'".indexOf(c) != -1) || (jTextFieldApellido.getText().length() >= 40)) {
            evt.consume(); // Consumir el evento para evitar que el carácter sea ingresado
            // Solo emitir el beep si no es la tecla de borrar
            if (c != KeyEvent.VK_BACK_SPACE) {
                Toolkit.getDefaultToolkit().beep();
            }
        }
        // Limpiar mensaje de error
        jLabelErrorApellido.setText("");
    }//GEN-LAST:event_jTextFieldApellidoKeyTyped

    /**
     * Maneja el evento de tecla presionada en el campo de DNI de usuario.
     * Limita la entrada a caracteres numéricos y no más de 8 dígitos. Emite un
     * sonido de advertencia si se excede el límite. Limpia el mensaje de error
     * asociado al campo.
     *
     * @param evt El evento de tecla presionada.
     */
    private void jTextFieldDNIUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDNIUserKeyTyped
        char c = evt.getKeyChar();
        //solo numeros
        if (!Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || (jTextFieldDNIUser.getText().length() >= 8)) {
            evt.consume();
            // Solo emitir el beep si no es la tecla de borrar
            if (c != KeyEvent.VK_BACK_SPACE) {
                Toolkit.getDefaultToolkit().beep();
            }
        }
        // Limpiar mensaje de error
        jLabelErrorDni.setText("");
    }//GEN-LAST:event_jTextFieldDNIUserKeyTyped

    /**
     * Maneja el evento de tecla presionada en el campo de tope de alumnos.
     * Limita la entrada a caracteres numéricos y no más de 3 dígitos. Emite un
     * sonido de advertencia si se excede el límite. Limpia el mensaje de error
     * asociado al campo.
     *
     * @param evt El evento de tecla presionada.
     */
    private void jTextFieldTopeAlumnosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTopeAlumnosKeyTyped
        char c = evt.getKeyChar();
        //solo numeros
        if (!Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || (jTextFieldTopeAlumnos.getText().length() >= 3)) {
            evt.consume();
            // Solo emitir el beep si no es la tecla de borrar
            if (c != KeyEvent.VK_BACK_SPACE) {
                Toolkit.getDefaultToolkit().beep();
            }
        }
        // Limpiar mensaje de error
        jLabelErrorTopeAlumnos.setText("");
    }//GEN-LAST:event_jTextFieldTopeAlumnosKeyTyped

    /**
     * Método principal que inicia la aplicación.
     *
     * @param args Los argumentos de la línea de comandos (no se utilizan en
     * esta aplicación).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroupTipoUsuario;
    public javax.swing.JButton jButtonBlanquearClave;
    public javax.swing.JButton jButtonBuscarUsuario;
    public javax.swing.JButton jButtonCambiarContraseña;
    public javax.swing.JButton jButtonCrearUsuario;
    public javax.swing.JButton jButtonModificarEstadoCurso;
    public javax.swing.JButton jButtonReactivarCuenta;
    public javax.swing.JButton jButtonSuspenderCuenta;
    public javax.swing.JComboBox<String> jComboBoxFiltroCursos;
    public javax.swing.JComboBox<String> jComboBoxModificarEstadoCurso;
    private javax.swing.JLabel jLabelApellido;
    public javax.swing.JLabel jLabelApellidoAdmin;
    private javax.swing.JLabel jLabelBusquedaUser;
    private javax.swing.JLabel jLabelDNIUsuario;
    private javax.swing.JLabel jLabelDatosUsuario;
    private javax.swing.JLabel jLabelDescripcionCursos;
    public javax.swing.JLabel jLabelDniAdmin;
    public javax.swing.JLabel jLabelErrorApellido;
    public javax.swing.JLabel jLabelErrorBuscarUsuario;
    public javax.swing.JLabel jLabelErrorDni;
    public javax.swing.JLabel jLabelErrorNombre;
    public javax.swing.JLabel jLabelErrorTopeAlumnos;
    private javax.swing.JLabel jLabelFiltroCurso;
    private javax.swing.JLabel jLabelModificarEstado;
    public javax.swing.JLabel jLabelNombreAdmin;
    private javax.swing.JLabel jLabelNombreUsuario;
    private javax.swing.JLabel jLabelTopeAlumnos;
    public javax.swing.JList<Curso> jListCursos;
    private javax.swing.JPanel jPanelAdmin;
    private javax.swing.JPanel jPanelCursos;
    private javax.swing.JPanel jPanelEstadoCuenta;
    private javax.swing.JPanel jPanelListadoUsuarios;
    public javax.swing.JPanel jPanelMiCuenta;
    private javax.swing.JPanel jPanelRegistroUser;
    private javax.swing.JPanel jPanelTipoUsuario;
    public javax.swing.JRadioButton jRadioButtonCuentaAlumno;
    public javax.swing.JRadioButton jRadioButtonCuentaDocente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTabbedPane jTabbedPaneAdmin;
    public javax.swing.JTable jTableListadoUsuarios;
    public javax.swing.JTextArea jTextAreaDescripcionCurso;
    public javax.swing.JTextArea jTextAreaEstadoCuenta;
    public javax.swing.JTextField jTextFieldApellido;
    public javax.swing.JTextField jTextFieldBuscarUsuario;
    public javax.swing.JTextField jTextFieldDNIUser;
    public javax.swing.JTextField jTextFieldNombreUser;
    public javax.swing.JTextField jTextFieldTopeAlumnos;
    // End of variables declaration//GEN-END:variables
}
