package visual;

import java.awt.Toolkit;

/**
 * La clase VentanaCambioPassword representa la interfaz gráfica de usuario para
 * el cambio de contraseña.
 */
public class VentanaCambioPassword extends javax.swing.JFrame {

    /**
     * Crea una nueva instancia de VentanaCambioPassword.
     */
    public VentanaCambioPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCambioPassword = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonCambioPassword = new javax.swing.JButton();
        jPasswordFieldActual = new javax.swing.JPasswordField();
        jPasswordFieldNueva = new javax.swing.JPasswordField();
        jPasswordFieldConfirmar = new javax.swing.JPasswordField();
        jLabelErrorContraseñaActual = new javax.swing.JLabel();
        jLabelErrorContraseñaNueva = new javax.swing.JLabel();
        jLabelErrorConfirmarContraseña = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Cambio de contraseña");

        jLabel2.setText("Contraseña actual:");

        jLabel3.setText("Contraseña nueva:");

        jLabel4.setText("Confirmar contraseña:");

        jButtonCambioPassword.setText("Guardar cambios");
        jButtonCambioPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCambioPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambioPasswordActionPerformed(evt);
            }
        });

        jPasswordFieldActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldActualKeyTyped(evt);
            }
        });

        jPasswordFieldNueva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldNuevaKeyTyped(evt);
            }
        });

        jPasswordFieldConfirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldConfirmarKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("(Debe contener 8 caracteres y ser distinta al DNI)");

        javax.swing.GroupLayout jPanelCambioPasswordLayout = new javax.swing.GroupLayout(jPanelCambioPassword);
        jPanelCambioPassword.setLayout(jPanelCambioPasswordLayout);
        jPanelCambioPasswordLayout.setHorizontalGroup(
            jPanelCambioPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCambioPasswordLayout.createSequentialGroup()
                .addGroup(jPanelCambioPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCambioPasswordLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(jPanelCambioPasswordLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCambioPasswordLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanelCambioPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCambioPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCambioPasswordLayout.createSequentialGroup()
                                .addComponent(jPasswordFieldActual, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelErrorContraseñaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCambioPasswordLayout.createSequentialGroup()
                                .addGroup(jPanelCambioPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPasswordFieldConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordFieldNueva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCambioPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelErrorConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelErrorContraseñaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonCambioPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelCambioPasswordLayout.setVerticalGroup(
            jPanelCambioPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCambioPasswordLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCambioPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorContraseñaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCambioPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanelCambioPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordFieldNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelErrorContraseñaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelCambioPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordFieldConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelErrorConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButtonCambioPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCambioPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCambioPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCambioPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambioPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCambioPasswordActionPerformed

    /**
     * Método invocado cuando se presiona una tecla en el campo de contraseña
     * actual. Verifica si se excede la longitud máxima y muestra un mensaje de
     * error si es necesario.
     *
     * @param evt el evento de teclado generado
     */
    private void jPasswordFieldActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldActualKeyTyped
        //Verificar si se excede la longitud máxima
        if (jPasswordFieldActual.getText().length() >= 8) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();// Consumir el evento para evitar que se ingrese el carácter
        }
        // Limpiar mensaje de error
        jLabelErrorContraseñaActual.setText("");
        jLabelErrorContraseñaNueva.setText("");
        jLabelErrorConfirmarContraseña.setText("");
    }//GEN-LAST:event_jPasswordFieldActualKeyTyped

    /**
     * Método invocado cuando se presiona una tecla en el campo de contraseña
     * nueva. Verifica si se excede la longitud máxima y muestra un mensaje de
     * error si es necesario.
     *
     * @param evt el evento de teclado generado
     */
    private void jPasswordFieldNuevaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldNuevaKeyTyped
        //Verificar si se excede la longitud máxima
        if (jPasswordFieldNueva.getText().length() >= 8) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();// Consumir el evento para evitar que se ingrese el carácter
        }
        // Limpiar mensaje de error
        jLabelErrorContraseñaNueva.setText("");
    }//GEN-LAST:event_jPasswordFieldNuevaKeyTyped

    /**
     * Método invocado cuando se presiona una tecla en el campo de confirmación
     * de contraseña. Verifica si se excede la longitud máxima y muestra un
     * mensaje de error si es necesario.
     *
     * @param evt el evento de teclado generado
     */
    private void jPasswordFieldConfirmarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmarKeyTyped
        //Verificar si se excede la longitud máxima
        if (jPasswordFieldConfirmar.getText().length() >= 8) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();// Consumir el evento para evitar que se ingrese el carácter
        }
        // Limpiar mensaje de error
        jLabelErrorConfirmarContraseña.setText("");
    }//GEN-LAST:event_jPasswordFieldConfirmarKeyTyped

    /**
     * Método principal para ejecutar la aplicación. Crea una instancia de la
     * ventana de cambio de contraseña, haciéndola visible.
     *
     * @param args los argumentos de la línea de comandos (no se utilizan en
     * esta aplicación)
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCambioPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCambioPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCambioPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCambioPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCambioPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCambioPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabelErrorConfirmarContraseña;
    public javax.swing.JLabel jLabelErrorContraseñaActual;
    public javax.swing.JLabel jLabelErrorContraseñaNueva;
    private javax.swing.JPanel jPanelCambioPassword;
    public javax.swing.JPasswordField jPasswordFieldActual;
    public javax.swing.JPasswordField jPasswordFieldConfirmar;
    public javax.swing.JPasswordField jPasswordFieldNueva;
    // End of variables declaration//GEN-END:variables
}
